version: '3.3'

services:
  tagd-consumers-app:
    image: tagd-consumers-app
    build:
      context: ../
      dockerfile: ${DTK_HOME}/dev/vuejs/node/16/buster-slim/Dockerfile
      args:
        DTK_VERSION: ${DTK_VERSION}
    container_name: tagd-consumers-app
    hostname: tagd-consumers-app
    ports:
      - 3103:3103
    restart: always
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ../:/app
    environment:
      - PORT=3103
      - NODE_UID=${USER_ID}
      - NODE_GUID=${GROUP_ID}

networks:
  default:
    external:
      name: dev
